codema-dev/projects

.gitignore, add_berpublicsearch_to_stock.py
To create a complete, live residential building stock
=> Add >2011 bldgs from BER PS to <2011 bldgs

environment.yml, get_stock_annual_totals.py
Can link these totals to the GNI Postcode gas
demand data averages to get rough heat demand estimates
=> Get total annual stock numbers

notebooks/get_stock_annual_totals.py
With a column of postcode totals per year
=> Save stock totals in same format as annual gas

data/benchmarks/benchmarks.csv
So can filter out SEUs in non-resi heat demand maps
=> Flag SEUs in benchmarks

dublin_building_stock/join.py, notebooks/estimate_small_area_resi_heat_demand_density_from_gas_average.py
Using the 2016 Census building stock & Gas Network Irelands
2019 Dublin Gas Consumption average estimate Heat Demand
per unit area in TJ/y.km^2
This estimate can be used in finding areas suitable for District
heating or having a HDD > 150 TK/y.km^2
=> Estimate Residential Heat Demand Density via Gas Avg

dublin_building_stock/__init__.py, dublin_building_stock/download.py, dublin_building_stock/get.py, dublin_building_stock/unzip.py
=> Add helper files to dublin_building_stock repo

notebooks/amalgamate_seda_2015_comm_stock.py
So instead of 4 separate local authority valuation office files
for 2015 have 1 clean geosjon
=> Amalgamate SEDA 2015 Commercial stock Local Authorities

notebooks/estimate_residential_building_growth_to_2030.py
As according to the BER vs age distribution most
buildings post 2011 are B2+ rated
=> Predict all Dublin HH growth from 2011

notebooks/get_data.py, notebooks/plot_ber_ratings.py
Previously excluded this category as it's not possible
to match it to a BER. Should be included as otherwise
the total category is incomplete
=> Plot 'not stated' period built as 'unknown' ber

notebooks/plot_ber_ratings.py
Join on matching small area ids rather than on matching indexes...
=> BUG: Join Small Area Statistics to Correct Geometries

dublin_building_stock/non_residential.py, dublin_building_stock/spatial_operations.py, notebooks/get_data.py, notebooks/non_residential.py
`get_data.py` notebook was becoming huge and
unmanageable, new refactored functions are clean and
can be incorporated into an ETL tool
=> Refactor Non-Residential get_data into functions

notebooks/amalgamate_2011_census_with_closed_ber.py
Enables creation of a building stock at 2016 Small Area
level that is up-to-date as of summer 2020 with around
half of the stock filled with BER ratings
=> Amalgamate pre 2011 census with post 2011 BER private

.gitignore, dublin_building_stock/download.py, notebooks/download_data.py
So more readable download utilities than get_data.py notebook,
can further refactor this notebook into an ETL
=> Refactor download data into own notebook

dublin_building_stock/residential.py, notebooks/wrangle_residential.py
Instead of huge get_data.py notebook have a collection of
create_NAME_DATA functions that am calling in a considerably
smaller notebook
=> Refactor Residential wrangling to file

dublin_building_stock/residential.py, notebooks/wrangle_residential.py
So can publish the Census 2011 stock along
with a Dublin extract of BER Public that can
be used to demonstrate the Heat Loss Parameter
methodology
=> Anonymise 2011 Census to Routing Keys

dublin_building_stock/residential.py, notebooks/plot_heat_pump_viability.py, notebooks/wrangle_residential.py
Previously assumed that all buildings not in the BER dataset
weren't heat pump ready.  Plotting building age vs heat loss
parameter shows this to be a poor assumption for buildings built
after the 60s so am now instead using a combination of calculated
HLP and inferred values from the building's age
=> Add inferred heat pump readiness to hp viability plot

notebooks/plot_boilers.py, notebooks/wrangle_residential.py
Can use this boiler total to very roughly estimate the total Dublin heat
demand using GNI Gas consumption totals.  This can be used for
model validation / rule of thumb ballpark okay heat demand estimates
=> Plot Dublin Boiler Total by Local Authority

notebooks/plot_boilers.py
=> Rename hovertool to Boiler in Boiler Breakdown map

notebooks/wrangle_boundaries.py
So can extract Small Areas by LA on maps
=> Link 2011 SAs to LAs

notebooks/wrangle_non_residential.py
Extract corresponding categories from VO and use Google MyMaps plot of
extracted locations to visually link each EPA building to its likely
VO match
=> Link EPA locations to VO locations

dublin_building_stock/non_residential.py, dublin_building_stock/residential.py, notebooks/amalgamate_building_stock.py, notebooks/wrangle_non_residential.py, notebooks/wrangle_residential.py
Combine Residential & Non-Residential Building stocks to
estimate total building emissions bottom-up for Dublin
=> Amalgamate building stocks

dublin_building_stock/download.py, environment.yml
So if an invalid request is made by download downloading is
interrupted
=> Raise 404 exception on download

dublin_building_stock/deap.py, dublin_building_stock/residential.py, tests/test_deap.py
Ensure that the DEAP Python calc is producing the same outputs as the
Excel version of DEAP 4.2.0 at https://www.seai.ie/home-energy/building-energy-rating-ber/support-for-ber-assessors/domestic-ber-resources/
=> Test DEAP HLP calc vs DEAP 4.2.0 Example A

dublin_building_stock/residential.py, notebooks/wrangle_ber_private.py, notebooks/wrangle_ber_public.py, notebooks/wrangle_residential.py
Using the tested HLP function in place of the pandas pipeline
=> Calculate HLP for both BER stocks

.gitignore, data/epa_ets_site_data.json, notebooks/wrangle_epa_ets_sites.py
Required to make EPA ETS wrangling reproducible
=> Add EPA ETS Site Data

notebooks/wrangle_tabula.py
So can link the stock in dublin-energy-app to TABULA typologies to
guess suitable retrofits and associated costs in each area
=> Wrangle tabula-calculator.xlsx into Typologies

notebooks/wrangle_small_area_boundaries_2011.py
Create a new file just to wrangle this dataset as easier to change than
wrangle_boundaries.py file.  Now Dublin SA Boundaries are also linked
to Routing Key Boundaries so can easily merge SAs with Postcode-level
data on top of SAs or EDs
=> Wrangle SA Boundaries 2011

notebooks/wrangle_dublin_local_authority_boundaries.py
Extract Dublin LA Boundaries from Ireland Boundaries in its own
script
=> Wrangle Dublin Local Authority Boundaries

notebooks/wrangle_dublin_local_authority_boundaries.py, notebooks/wrangle_routing_key_boundaries.py
In own file separate to notebooks/wrangle_boundaries.py
=> Extract Dublin Routing Key Boundaries

notebooks/wrangle_census2011_private.py
Combine specially-requested Dublin Small Area cross-tabulated
census extract for all LAs and expand into individual builings...
=> Wrangle Census 2011 Private

notebooks/wrangle_postcode_boundaries.py, notebooks/wrangle_routing_key_boundaries.py
So can use this distance as a feature for archetyping
=> Calculate Postcode Distance to City Centre

notebooks/wrangle_ber_public.py
So can use this as a feature for archetyping
=> Link BER Public to Dist to City centre

notebooks/download_data.py, notebooks/wrangle_small_area_boundaries_2011.py
- Add distance from sa centroid to city centre
=> Add distance from sa centroid to city centre

notebooks/create_wall_archetypes.py, notebooks/download_data.py, notebooks/wrangle_small_area_boundaries_2011.py
- Create modal wall archetype by distance from cc and dwelling type
=> Create wall archetypes

notebooks/wrangle_ber_private.py
Don't use a function but do in-script instead
=> Wrangle BER Private in-notebook

notebooks/create_wall_archetypes.py
Enables probability-based estimation of wall type for unknown
buildings using the open-access BER Public dataset
=> Create probabilistic wall type archetypes

heritage-buildings/README.md, heritage-buildings/environment.yml, heritage-buildings/pipeline.yaml, heritage-buildings/tasks.py
Enables mapping of zones that are not suitable for bulk retrofit plans due to high numbers of heritage buildings
=> Map SMR & NIAH heritage houses

README.md, environment.meta.yml, environment.yml, tasks.py
Can now run codema-dev/projects in the browser via binder which will automatically install all dependencies listed in environment.yml
=> Merge environment ymls for binder

environment.yml, heritage-buildings/environment.yml, lv-grid-capacity/environment.yml, plot-district-heating-viability/environment.yml, plot-heat-pump-viability/environment.yaml, road-line-lengths/environment.yml
- codema-dev-tasks==0.1.0 not git+
- pygraphviz via conda instead of pip install graphviz
- remove dataframe-image
=> Remove unnecessary pip dependencies

.gitpod.yml
So every time the shell restarts can still use conda
=> Add conda micromamba alias to gitpod bashrc
